image: "rust:latest"

default:
  before_script:
    - rustc --version 
    - cargo --version

stages:
  - test

lint-code:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy -- -D warnings

audit-code:
  stage: test
  script:
    - cargo install cargo-audit
    - cargo audit
